@startuml

class TarjetaSubte {
  - CentralSubtes central
  - double saldo

  + TarjetaSubte(CentralSubtes central)
  + void viajar()
  - boolean puedoViajar()
  + void recargar(double monto)
  + double get_saldo()
}

class CentralSubtes {
  - double precio_viaje
  
  + CentralSubtes(double precio)
  + void set_precio_viaje(double nuevo_precio)
}

TarjetaSubte *-- CentralSubtes

@enduml

