class Coordinate {
  - latitude : double
  - longitude : double

  + Coordinate(latitude : double, longitude : double)
  + void set_latitude(latitude : double)
  + void set_longitude(latitude : double)
  + void get_latitude()
  + void get_longitude()
  + char get_hemisphere()
  - boolean is_southern()
  - boolean is_western()
}

