abstract class GeometricFigure {
  {abstract} + get_base() double
  {abstract} + get_height() double
  {abstract} + get_area() double
  {abstract} + get_perimeter() double
}

class Rectangle {
  - triangle : RectangularTriangle

  + Rectangle(p1 : Point, p2 : Point, p3 : Point)
  + get_base() double
  + get_height() double
  + get_area() double
  + get_perimeter() double
}

note right to Rectangle
  Notemos que un rectangulo tiene dos triangulos ( aunque con uno nos alcanza )
  ademas con 3 puntos nos alcanza porque tendriamos la base y la altura
end note

abstract class Triangle {
  - p1, p2, p3 : Point

  + RectangularTriangle(p1 : Point, p2 : Point, p3 : Point)
  + base() double
  + height() double
  + get_area() double
  + get_perimeter() double
}

class Point {
  - x : double
  - y : double

  + Point(x : double, y : double)
  + distance_to(to : Point to) double
}

